# Generated by Django 5.2 on 2025-08-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nombre',
        ),
    ]
